# Generated by Django 3.1.2 on 2020-10-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201005_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jobtemplate'),
        ),
    ]
