# Generated by Django 3.1.2 on 2020-10-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='variables',
            field=models.JSONField(),
        ),
    ]
