# Generated by Django 3.1.2 on 2020-10-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201012_0810'),
        ('api', '0004_inventory_type'),
    ]

    operations = [
    ]
