# Generated by Django 3.1.2 on 2020-10-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_inventory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='input',
            field=models.TextField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='variables',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
