# Generated by Django 3.1.2 on 2020-10-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201012_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_scheduled',
            field=models.DateTimeField(null=True, verbose_name='Date Scheduled'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Scheduled'), (2, 'Running'), (3, 'Finished'), (4, 'Failed'), (5, 'Aborted')], default=0),
        ),
    ]
