# Generated by Django 3.1.2 on 2020-10-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201012_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='filters',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='result_host_selection',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='variables',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
