# Generated by Django 3.1.2 on 2020-10-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_task_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.inventory'),
        ),
    ]
