# Generated by Django 3.1.2 on 2020-10-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_task_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtemplate',
            old_name='file_path',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='function_name',
            field=models.TextField(default='job_function'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='package_path',
            field=models.TextField(default='/web_nornir/job_templates/'),
        ),
    ]
