# Generated by Django 3.1.2 on 2020-10-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201023_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='variables',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
