# Generated by Django 3.1.2 on 2020-10-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_jobtemplate_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplate',
            name='variables',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
