# Generated by Django 3.1.2 on 2020-11-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_inventory_defaults_file'),
        ('api', '0016_auto_20201030_1500'),
    ]

    operations = [
    ]
